# Generated by Django 3.0.4 on 2020-03-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ransomware', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infectedpc',
            name='paymentStatus',
            field=models.BooleanField(default=False),
        ),
    ]
