# Generated by Django 3.0.4 on 2020-04-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ransomware', '0003_auto_20200405_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infectedpc',
            name='privateKey',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='infectedpc',
            name='publicKey',
            field=models.CharField(max_length=2048),
        ),
    ]
